chore: checkpoint

diff --git a/.github/workflows/fair.yml b/.github/workflows/fair.yml
--- a/.github/workflows/fair.yml
+++ b/.github/workflows/fair.yml
@@ -602,6 +602,46 @@ jobs:
           freshclam -v
           clamscan /etc/hosts
 
+      - name: "Generate iOS fairseal"
+        if: ${{ inputs.target_ios == true && steps.platforms.outputs.ios == 'enabled' }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
+        run: |
+          # build the URL for the GitHub download artifact
+          IPAURL="https://github.com/${{ env.ORGNAME }}/App/releases/download/${{ steps.get_semver_tag.outputs.semver_tag }}/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" 
+
+          # virus/malware scan
+          # mkdir -p staging/.artifact_scan
+          # cd staging/.artifact_scan
+          # curl --retry-max-time 300 --retry 25 --retry-all-errors -fsSL -o untrusted.ipa "${IPAURL}"
+          # clamscan -v --heuristic-scan-precedence=yes --scan-archive=yes untrusted.ipa
+          # cd -
+
+          echo "Generating fairseal for: $IPAURL"
+
+          mkdir -p staging/.artifact_stash/
+          mv -f staging/*.zip staging/.artifact_stash/ || true # don't seal the macOS zip for iOS seal
+
+          # Builds on iOS are currently not reproducible (help wanted!),
+          # so we accept a large diff tolerance for permitted-diffs
+          fairtool-head fair fairseal \
+            --verbose \
+            --hub "github.com/${{ inputs.fairground }}" \
+            --base-repo "App" \
+            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
+            --org "${{ env.ORGNAME }}" \
+            --fairseal-key "${{ secrets.APP_FAIR_FAIRSEAL_KEY }}" \
+            --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" \
+            --permitted-diffs 100000000 \
+            --retry-duration 600 \
+            --artifact-url "$IPAURL" \
+            --artifact-staging "staging/" \
+            --fair-properties "${{ env.IR_TARGET }}/AppFairApp.xcconfig" \
+            --accent-color "${{ env.IR_TARGET }}/Assets.xcassets/AccentColor.colorset/Contents.json" \
+            --project .
+
+          mv -f staging/.artifact_stash/* staging/ || true # restore stash
+
       # compare the contents of the PR's un-trusted artifacts with
       # the contents of the base fair-ground's trusted artifacts
       - name: "Generate macOS fairseal"
@@ -642,46 +682,6 @@ jobs:
             --permitted-diffs 0 \
             --retry-duration 600 \
             --artifact-url "$ZIPURL" \
-            --artifact-staging "staging/" \
-            --fair-properties "${{ env.IR_TARGET }}/AppFairApp.xcconfig" \
-            --accent-color "${{ env.IR_TARGET }}/Assets.xcassets/AccentColor.colorset/Contents.json" \
-            --project .
-
-          mv -f staging/.artifact_stash/* staging/ || true # restore stash
-
-      - name: "Generate iOS fairseal"
-        if: ${{ inputs.target_ios == true && steps.platforms.outputs.ios == 'enabled' }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
-        run: |
-          # build the URL for the GitHub download artifact
-          IPAURL="https://github.com/${{ env.ORGNAME }}/App/releases/download/${{ steps.get_semver_tag.outputs.semver_tag }}/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" 
-
-          # virus/malware scan
-          # mkdir -p staging/.artifact_scan
-          # cd staging/.artifact_scan
-          # curl --retry-max-time 300 --retry 25 --retry-all-errors -fsSL -o untrusted.ipa "${IPAURL}"
-          # clamscan -v --heuristic-scan-precedence=yes --scan-archive=yes untrusted.ipa
-          # cd -
-
-          echo "Generating fairseal for: $IPAURL"
-
-          mkdir -p staging/.artifact_stash/
-          mv -f staging/*.zip staging/.artifact_stash/ || true # don't seal the macOS zip for iOS seal
-
-          # Builds on iOS are currently not reproducible (help wanted!),
-          # so we accept a large diff tolerance for permitted-diffs
-          fairtool-head fair fairseal \
-            --verbose \
-            --hub "github.com/${{ inputs.fairground }}" \
-            --base-repo "App" \
-            --token "${{ secrets.APP_FAIR_BOT_TOKEN }}" \
-            --org "${{ env.ORGNAME }}" \
-            --fairseal-key "${{ secrets.APP_FAIR_FAIRSEAL_KEY }}" \
-            --trusted-artifact "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa" \
-            --permitted-diffs 100000000 \
-            --retry-duration 600 \
-            --artifact-url "$IPAURL" \
             --artifact-staging "staging/" \
             --fair-properties "${{ env.IR_TARGET }}/AppFairApp.xcconfig" \
             --accent-color "${{ env.IR_TARGET }}/Assets.xcassets/AccentColor.colorset/Contents.json" \
